### PR TITLE
Basic Layout of the program

### PR DESCRIPTION
**Pull request by IssacL891**
Login should work. 
Steps to run : 
1. ./gradlew instalDist
2. Enter Build Scripts 
3. Enter Bin
4. Run either ./CLI (Mac / Linux) or ./CLI.bat for Windows
5. Once running, Run help for further instructions

Known Issues:
1. ~Hangs on exit will fix on later PR~ FIXED

### CODE REVIEW

**Review by Yiroh — APPROVED** [review]
Reviewed the changes, tested and user is able to login and get information from the tables, well done! For a basic layout, its amazing and good start to cement things further!

**Comment by ew3797** [comment]
Works for me!

**Review by ew3797 — APPROVED** [review]

**Review by dbo8671 — APPROVED** [review]
lgtm

**Comment by Yiroh** [comment]
> Could you guys check if the fix works for you?

Yes, no longer hanging on exit!

**Review by Yiroh — APPROVED** [review]
With the added fix, everything seems to be good on my end!

**Pull request merged**
